/* Generated By:JavaCC: Do not edit this line. MiniTriangle.java */
import java.io.File;
import java.io.FileNotFoundException;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

public class MiniTriangle implements MiniTriangleConstants {

  public static String CAMINHO_ARQUIVO = "resultados.mt.txt";

  // contador das regras de producao
  public int contadorProgram = 0;
  public int contadorCommand = 0;
  public int contadorSingleCommand = 0;
  public int contadorExpression = 0;
  public int contadorPrimaryExpression = 0;
  public int contadorDeclaration = 0;
  public int contadorSingleDeclaration = 0;
  public int contadorTypeDenoter = 0;
  public int contadorIntegerLiteral = 0;

  public int contadorOperator = 0;
  public List<String > listaOperators = new ArrayList<String>();
  public int contadorAssignmentOperator = 0;
  public int contadorTypeAnnotation = 0;

  public int contadorIdentificadores = 0;
  public List<String> listaIdentificadores = new ArrayList<String>();

  public Map<String, List<String>> tabelaVariaveis = new HashMap<String, List<String>>();

  public int contadorCondicionais = 0;
  public int contadorLoops = 0;
  public int contadorDeclaracoesConst = 0;
  public int contadorDeclaracoesVar = 0;

  public boolean temProgram = false;
  public boolean temCommand = false;
  public boolean temSingleCommand = false;
  public boolean temExpression = false;
  public boolean temPrimaryExpression = false;
  public boolean temDeclaration = false;
  public boolean temSingleDeclaration = false;
  public boolean temTypeDenoter = false;
  public boolean temIntegerLiteral = false;
  public boolean temOperator = false;

    public static void main(String[] args) {

                MiniTriangle parser;

                try {

                        if (args.length > 0) {

                                String filename = args[0];
                                parser = new MiniTriangle(new java.io.FileInputStream(filename));


                                System.out.println("\n===\tGERANDO PARSER\t===\n");
                                System.out.println("\tParser do programa: " + filename);

                        } else {

                        System.out.println("Digite um programa Mini-Triangle e aperte Enter + Ctrl+D (ou Ctrl+Z): ");

                                parser = new MiniTriangle(System.in);


                        }

                        parser.Iniciar();

                } catch (FileNotFoundException ex) {

                        System.err.println("Erro: O arquivo especificado n\u00e3o foi encontrado.");

                } catch (ParseException ex) {

                        System.err.println("\nErro de sintaxe: " + ex.getMessage());

                } catch (TokenMgrError ex) {

                        System.err.println("\nErro lexico (Caracter invalido): " + ex.getMessage());

                } catch (Exception ex) {

                        System.err.println("\nErro inesperado: " + ex.getMessage());

                }

    }

    public boolean possuiTodasAsProducoes() {

        return
            temProgram &&
                temCommand &&
                temSingleCommand &&
                temExpression &&
                temPrimaryExpression &&
                temDeclaration &&
                temSingleDeclaration &&
                temTypeDenoter &&
                temIntegerLiteral &&
                temOperator;
    }

    public String booleanParaSimNao(boolean expressao) {
                return expressao ? "Sim" : "N\u00e3o";
    }

    public void detalharResultados() {

                BufferedWriter bw = null;

                try {

                        bw = new BufferedWriter(new FileWriter(CAMINHO_ARQUIVO, true));

                        // titulo
                        bw.write("RESULTADOS DO PARSER");
                        bw.newLine();

                        //
                        bw.write("Possui todas as regras de produ\u00e7\u00e3o: " + possuiTodasAsProducoes());
                        bw.newLine();
                        bw.write("\tTem 'Command': " + booleanParaSimNao(temCommand));
                        bw.newLine();
                        bw.write("\tTem 'Single Command': " + booleanParaSimNao(temSingleCommand));
                        bw.newLine();
                        bw.write("\tTem 'Expression': " + booleanParaSimNao(temExpression));
                        bw.newLine();

                } catch (IOException ex) {
                        System.err.println("\nErro na escrita do arquivo: " + ex.getMessage());
                } finally {
                        if (bw != null) {
                                try {
                                        bw.close();
                                } catch (IOException ex) {
                                        System.err.println("Erro ao fechar o recurso de escrita: " + ex.getMessage());
                                }
                        }
                }

    }

// INÍCIO
  final public void Iniciar() throws ParseException {
    Program();
                System.out.println("Possui todas as regras de produ\u00e7\u00e3o: " + (possuiTodasAsProducoes() ? "Sim" : "N\u00e3o"));
                System.out.println("Inicia com 'Program': " + (contadorProgram == 1 ? "Sim" : "N\u00e3o"));

                System.out.println("Quantidade de 'Command': " + contadorCommand);
                System.out.println("Quantidade de 'SingleCommand': " + contadorSingleCommand);
                System.out.println("Quantidade de 'Expression': " + contadorExpression);
                System.out.println("Quantidade de 'PrimaryExpression': " + contadorPrimaryExpression);
                System.out.println("Quantidade de 'Declaration': " + contadorDeclaration);
                System.out.println("Quantidade de 'SingleDeclaration': " + contadorSingleDeclaration);
                System.out.println("Quantidade de 'TypeDenoter': " + contadorTypeDenoter);
                System.out.println("Quantidade de 'IntegerLiteral': " + contadorIntegerLiteral);
                System.out.println("Quantidade de 'Operator': " + contadorOperator);

                System.out.println("Lista de Operadores: " + listaOperators);

                System.out.println("Quantidade de 'Assignment Operator': " + contadorAssignmentOperator);
                System.out.println("Quantidade de 'Type Annotation': " + contadorTypeAnnotation);

                System.out.println("Quantidade de Condicionais: " + contadorCondicionais);
                System.out.println("Quantidade de Loops: " + contadorLoops);

                System.out.println("Identificadores: " + contadorIdentificadores);
                System.out.println("Declara\u00e7\u00f5es:\n-- Const: " + contadorDeclaracoesConst + "\n-- Var: " + contadorDeclaracoesVar);

                System.out.println("Quantidade de Identificadores \u00danicos: " + listaIdentificadores.size());
                System.out.println("Lista de Identificadores \u00danicos: " + listaIdentificadores);

                System.out.println("\n\nTabela de Variaveis:");
                for (String tipo : tabelaVariaveis.keySet()) {
                        System.out.println("* " + tipo + ": ");

                        System.out.println(tabelaVariaveis.get(tipo));
                }

                detalharResultados();
  }

/*
<Program> ::= <single-Command>
*/
  final public void Program() throws ParseException {
        Token token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PROGRAM:
      jj_consume_token(PROGRAM);
      token = jj_consume_token(IDENTIFIER);
        temProgram = true;

        contadorProgram++;
                contadorIdentificadores++;

                if (!listaIdentificadores.contains(token.image)) {
                        listaIdentificadores.add(token.image);
                }
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    Command();
        temCommand = true;
        contadorCommand++;
    jj_consume_token(0);
  }

/*
<Command> ::= <single-Command>
		| <Command> “;” <single-Command>
*/
  final public void Command() throws ParseException {
    SingleCommand();
              temSingleCommand = true;
              contadorSingleCommand++;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SEMICOLON:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      jj_consume_token(SEMICOLON);
      SingleCommand();
                contadorSingleCommand++;
    }
  }

/*
<single-Command> ::=
			<V-name> := <Expression>
			| <Identifier> “(“ <Expression> “)”
			| IF <Expression>
			  THEN <single-Command>
			  ELSE <single-Command>
			| WHILE <Expression>
			  DO <single-command>
			| LET <Declaration>
			  IN <single-Command>
			| BEGIN <Command> END
*/
  final public void SingleCommand() throws ParseException {
        Token token;
    if (jj_2_1(2)) {
      token = jj_consume_token(IDENTIFIER);
                        contadorIdentificadores++;

                        if (!listaIdentificadores.contains(token.image)) {
                                        listaIdentificadores.add(token.image);
                        }
      AssignmentOperator();
      Expression();
                        temExpression = true;
                        contadorExpression++;
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        token = jj_consume_token(IDENTIFIER);
                        contadorIdentificadores++;

                        if (!listaIdentificadores.contains(token.image)) {
                                        listaIdentificadores.add(token.image);
                        }
        jj_consume_token(LPAREN);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LPAREN:
        case SLASH:
        case LT:
        case GT:
        case PLUS:
        case MINUS:
        case EQ:
        case STAR:
        case BSLASH:
        case IDENTIFIER:
        case DIGIT:
          Expression();
                temExpression = true;
                        contadorExpression++;
          label_2:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case COMMA:
              ;
              break;
            default:
              jj_la1[2] = jj_gen;
              break label_2;
            }
            jj_consume_token(COMMA);
            Expression();
                                           contadorExpression++;
          }
          break;
        default:
          jj_la1[3] = jj_gen;
          ;
        }
        jj_consume_token(RPAREN);
        break;
      case IF:
        jj_consume_token(IF);
        Expression();
                        temExpression = true;
                        contadorExpression++;
        jj_consume_token(THEN);
        SingleCommand();
                                temSingleCommand = true;
                                contadorSingleCommand++;
        jj_consume_token(ELSE);
        SingleCommand();
                                contadorSingleCommand++;
                                contadorCondicionais++;
        break;
      case WHILE:
        jj_consume_token(WHILE);
        Expression();
                        temExpression = true;
                        contadorExpression++;
        jj_consume_token(DO);
        SingleCommand();
                        temSingleCommand = true;
                                contadorSingleCommand++;
                                contadorLoops++;
        break;
      case LET:
        jj_consume_token(LET);
        Declaration();
                                temDeclaration = true;
                                contadorDeclaration++;
        jj_consume_token(IN);
        SingleCommand();
                                temSingleCommand = true;
                                contadorSingleCommand++;
        break;
      case BEGIN:
        jj_consume_token(BEGIN);
        Command();
                                temCommand = true;
                                contadorCommand++;
        jj_consume_token(END);
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

/*
<Expression> ::= <primary-Expression>
		| <Expression> <Operator>
					<primary-Expression>
*/
  final public void Expression() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN:
      jj_consume_token(LPAREN);
      PrimaryExpression();
                        temPrimaryExpression = true;
                        contadorPrimaryExpression++;
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SLASH:
        case LT:
        case GT:
        case PLUS:
        case MINUS:
        case EQ:
        case STAR:
        case BSLASH:
          ;
          break;
        default:
          jj_la1[5] = jj_gen;
          break label_3;
        }
        Operator();
        PrimaryExpression();
                                                   contadorPrimaryExpression++;
      }
      jj_consume_token(RPAREN);
      break;
    case SLASH:
    case LT:
    case GT:
    case PLUS:
    case MINUS:
    case EQ:
    case STAR:
    case BSLASH:
    case IDENTIFIER:
    case DIGIT:
      PrimaryExpression();
                        temPrimaryExpression = true;
                        contadorPrimaryExpression++;
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SLASH:
        case LT:
        case GT:
        case PLUS:
        case MINUS:
        case EQ:
        case STAR:
        case BSLASH:
          ;
          break;
        default:
          jj_la1[6] = jj_gen;
          break label_4;
        }
        Operator();
        PrimaryExpression();
                                temPrimaryExpression = true;
                                contadorPrimaryExpression++;
      }
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/*
<primary-expression> ::= <Integer-Literal>
			| <V-name>
			| <Operator> <primary-Expression>
*/
  final public void PrimaryExpression() throws ParseException {
        Token token;
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SLASH:
      case LT:
      case GT:
      case PLUS:
      case MINUS:
      case EQ:
      case STAR:
      case BSLASH:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_5;
      }
      Operator();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DIGIT:
      IntegerLiteral();
                        temIntegerLiteral = true;
                        contadorIntegerLiteral++;
      break;
    case IDENTIFIER:
      token = jj_consume_token(IDENTIFIER);
                        contadorIdentificadores++;

                        if (!listaIdentificadores.contains(token.image)) {
                                        listaIdentificadores.add(token.image);
                        }
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/*
<Declaration> ::= <single-Declaration>
		| <Declaration> “;” <single-Declaration>
*/
  final public void Declaration() throws ParseException {
    SingleDeclaration();
                temSingleDeclaration = true;
                contadorSingleDeclaration++;
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SEMICOLON:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_6;
      }
      jj_consume_token(SEMICOLON);
      SingleDeclaration();
                                contadorSingleDeclaration++;
    }
  }

/*
<single-Declaration> ::= 
		CONST <Identifier> “~” <Expression>
		| VAR <Identifier> “:” <Type-denoter>
*/
  final public void SingleDeclaration() throws ParseException {
        Token token;
        String tipoVar;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONST:
      jj_consume_token(CONST);
                        contadorDeclaracoesConst++;
      token = jj_consume_token(IDENTIFIER);
                        contadorIdentificadores++;

                        if (!listaIdentificadores.contains(token.image)) {
                                        listaIdentificadores.add(token.image);
                        }
      AssignmentOperator();
      Expression();
                                contadorExpression++;
      break;
    case VAR:
      jj_consume_token(VAR);
        contadorDeclaracoesVar++;
      token = jj_consume_token(IDENTIFIER);
                        contadorIdentificadores++;

                        if (!listaIdentificadores.contains(token.image)) {
                                        listaIdentificadores.add(token.image);
                        }
      TypeAnnotation();
      tipoVar = TypeDenoter();
                        temTypeDenoter = true;
                                contadorTypeDenoter++;

                                if (!tabelaVariaveis.containsKey(tipoVar)) {
                                                tabelaVariaveis.put(tipoVar, new ArrayList<String>());
                                }

                                tabelaVariaveis.get(tipoVar).add(token.image);
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void TypeAnnotation() throws ParseException {
    jj_consume_token(COLON);
                        contadorTypeAnnotation++;
  }

/*
<Type-denoter> ::= <Identifier>
*/
  final public String TypeDenoter() throws ParseException {
        Token token;
    token = jj_consume_token(IDENTIFIER);
                        contadorIdentificadores++;

                        if (!listaIdentificadores.contains(token.image)) {
                                listaIdentificadores.add(token.image);
                        }

                        {if (true) return token.image;}
    throw new Error("Missing return statement in function");
  }

/*
<Integer-Literal> ::= <Digit>
		| <Integer-Literal> <Digit>
*/
  final public void IntegerLiteral() throws ParseException {
    jj_consume_token(DIGIT);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DIGIT:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_7;
      }
      jj_consume_token(DIGIT);
    }
        temIntegerLiteral = true;
  }

  final public void AssignmentOperator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGN:
      jj_consume_token(ASSIGN);
                        contadorAssignmentOperator++;
      break;
    case TILDE:
      jj_consume_token(TILDE);
                        contadorAssignmentOperator++;
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void Operator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LT:
      jj_consume_token(LT);
           contadorOperator++;
      break;
    case GT:
      jj_consume_token(GT);
             contadorOperator++;
      break;
    case EQ:
      jj_consume_token(EQ);
             contadorOperator++;
      break;
    case PLUS:
      jj_consume_token(PLUS);
               contadorOperator++;
      break;
    case MINUS:
      jj_consume_token(MINUS);
                contadorOperator++;
      break;
    case STAR:
      jj_consume_token(STAR);
               contadorOperator++;
      break;
    case SLASH:
      jj_consume_token(SLASH);
                contadorOperator++;
      break;
    case BSLASH:
      jj_consume_token(BSLASH);
                 contadorOperator++;
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_3R_9() {
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_8() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_9()) {
    jj_scanpos = xsp;
    if (jj_3R_10()) return true;
    }
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_3R_8()) return true;
    return false;
  }

  private boolean jj_3R_10() {
    if (jj_scan_token(TILDE)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public MiniTriangleTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[15];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x20,0x80000,0x100000,0xf2e20000,0x13040,0xf2e00000,0xf2e00000,0xf2e20000,0xf2e00000,0x0,0x80000,0x8080,0x0,0xc000000,0xf2e00000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x3,0x1,0x0,0x0,0x3,0x0,0x3,0x0,0x0,0x2,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniTriangle(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniTriangle(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MiniTriangleTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniTriangle(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MiniTriangleTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniTriangle(MiniTriangleTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniTriangleTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[35];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 15; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 35; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 1; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
