/* Generated By:JavaCC: Do not edit this line. MiniTriangleConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniTriangleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 5;
  /** RegularExpression Id. */
  int BEGIN = 6;
  /** RegularExpression Id. */
  int CONST = 7;
  /** RegularExpression Id. */
  int DO = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int IN = 11;
  /** RegularExpression Id. */
  int LET = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int THEN = 14;
  /** RegularExpression Id. */
  int VAR = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int LPAREN = 17;
  /** RegularExpression Id. */
  int RPAREN = 18;
  /** RegularExpression Id. */
  int SEMICOLON = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int SLASH = 21;
  /** RegularExpression Id. */
  int LT = 22;
  /** RegularExpression Id. */
  int GT = 23;
  /** RegularExpression Id. */
  int COLON = 24;
  /** RegularExpression Id. */
  int PLUS = 25;
  /** RegularExpression Id. */
  int ASSIGN = 26;
  /** RegularExpression Id. */
  int TILDE = 27;
  /** RegularExpression Id. */
  int MINUS = 28;
  /** RegularExpression Id. */
  int EQ = 29;
  /** RegularExpression Id. */
  int STAR = 30;
  /** RegularExpression Id. */
  int BSLASH = 31;
  /** RegularExpression Id. */
  int IDENTIFIER = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;
  /** RegularExpression Id. */
  int LETTER = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"program\"",
    "\"begin\"",
    "\"const\"",
    "\"do\"",
    "\"else\"",
    "\"end\"",
    "\"in\"",
    "\"let\"",
    "\"if\"",
    "\"then\"",
    "\"var\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\":\"",
    "\"+\"",
    "\":=\"",
    "\"~\"",
    "\"-\"",
    "\"=\"",
    "\"*\"",
    "\"\\\\\"",
    "<IDENTIFIER>",
    "<DIGIT>",
    "<LETTER>",
  };

}
