/* Generated By:JavaCC: Do not edit this line. MiniTriangleConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniTriangleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int PROGRAM = 6;
  /** RegularExpression Id. */
  int BEGIN = 7;
  /** RegularExpression Id. */
  int CONST = 8;
  /** RegularExpression Id. */
  int DO = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int END = 11;
  /** RegularExpression Id. */
  int IN = 12;
  /** RegularExpression Id. */
  int LET = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int THEN = 15;
  /** RegularExpression Id. */
  int VAR = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int INTEGER = 18;
  /** RegularExpression Id. */
  int STRING = 19;
  /** RegularExpression Id. */
  int FLOAT = 20;
  /** RegularExpression Id. */
  int BOOLEAN = 21;
  /** RegularExpression Id. */
  int LPAREN = 22;
  /** RegularExpression Id. */
  int RPAREN = 23;
  /** RegularExpression Id. */
  int SEMICOLON = 24;
  /** RegularExpression Id. */
  int COMMA = 25;
  /** RegularExpression Id. */
  int SLASH = 26;
  /** RegularExpression Id. */
  int LT = 27;
  /** RegularExpression Id. */
  int GT = 28;
  /** RegularExpression Id. */
  int COLON = 29;
  /** RegularExpression Id. */
  int PLUS = 30;
  /** RegularExpression Id. */
  int ASSIGN = 31;
  /** RegularExpression Id. */
  int TILDE = 32;
  /** RegularExpression Id. */
  int MINUS = 33;
  /** RegularExpression Id. */
  int EQ = 34;
  /** RegularExpression Id. */
  int STAR = 35;
  /** RegularExpression Id. */
  int BSLASH = 36;
  /** RegularExpression Id. */
  int IDENTIFIER = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;
  /** RegularExpression Id. */
  int LETTER = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "\"program\"",
    "\"begin\"",
    "\"const\"",
    "\"do\"",
    "\"else\"",
    "\"end\"",
    "\"in\"",
    "\"let\"",
    "\"if\"",
    "\"then\"",
    "\"var\"",
    "\"while\"",
    "<INTEGER>",
    "<STRING>",
    "\"float\"",
    "<BOOLEAN>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\":\"",
    "\"+\"",
    "\":=\"",
    "\"~\"",
    "\"-\"",
    "\"=\"",
    "\"*\"",
    "\"\\\\\"",
    "<IDENTIFIER>",
    "<DIGIT>",
    "<LETTER>",
  };

}
